// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJXGyJ3xUYHu4kBftvi0Iz_W9lomwsbnM',
    appId: '1:1039262752298:web:f2aaf285e4beae2edced53',
    messagingSenderId: '1039262752298',
    projectId: 'testi-1dd0b',
    authDomain: 'testi-1dd0b.firebaseapp.com',
    storageBucket: 'testi-1dd0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdz8GWh7LFWNAur25CRv_Mc7Hg4hDP0Aw',
    appId: '1:1039262752298:android:1e14f277e20293afdced53',
    messagingSenderId: '1039262752298',
    projectId: 'testi-1dd0b',
    storageBucket: 'testi-1dd0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbi21rSpjIY88mc_SmWvEV_Vni5_RSNdU',
    appId: '1:1039262752298:ios:99bc556f5625eb95dced53',
    messagingSenderId: '1039262752298',
    projectId: 'testi-1dd0b',
    storageBucket: 'testi-1dd0b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbi21rSpjIY88mc_SmWvEV_Vni5_RSNdU',
    appId: '1:1039262752298:ios:a9c8169523187f05dced53',
    messagingSenderId: '1039262752298',
    projectId: 'testi-1dd0b',
    storageBucket: 'testi-1dd0b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
